language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
    - ~/.node_modules
    - ~/.cache
    - ~/.cache/Cypress

jobs:
  include:
    - stage: test
      script:
        - yarn install
        - yarn test
        - yarn build
        - yarn e2e:build
        - yarn test:e2e:ci
